"""
Build final wordlists from classification results + morphological expansion.

Outputs (all JSONL, one object per line):
  wordlist_accepted.jsonl        — valid words (LLM-accepted + morphological expansions)
  data/wordlist_rejected.jsonl   — invalid words (large, gitignored)
  wordlist_uncertain.jsonl       — uncertain words (not included in accepted list)

Source field values:
  "llm"             — classified directly by the LLM
  "morphology"      — net-new form generated by morphological expansion from an LLM-accepted lemma

Verified-by values:
  "deepseek-chat"   — DeepSeek V3, triple-pass (2× normal/reversed + tiebreaker), t=0.3
  "kaikki+deepseek-chat" — morphological form from Kaikki Wiktionary, base word verified by above

Usage:
  python3 -m scripts.build_wordlists
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

TSV_PATH = Path("data/calibration_frac1_gosd_full_deepseek_t0p3_double_results.tsv")
EXPANDED_PATH = Path("data/morphology_expanded_full.txt")
OUT_ACCEPTED = Path("wordlist_accepted.jsonl")
OUT_REJECTED = Path("data/wordlist_rejected.jsonl")
OUT_UNCERTAIN = Path("wordlist_uncertain.jsonl")

VERIFIED_BY_LLM = "deepseek-chat"
VERIFIED_BY_MORPH = "kaikki+deepseek-chat"


def model_pass_label(model_field: str) -> str:
    """Human-readable label for which pass resolved the classification."""
    if model_field == "haiku_agree":
        return "double-pass-agree"
    if model_field == "deepseek_tie":
        return "tiebreaker"
    return model_field


def parse_sources(sources_str: str) -> list[str]:
    if not sources_str:
        return []
    return [s.strip() for s in sources_str.split(",") if s.strip()]


def main() -> None:
    print("Reading TSV...", file=sys.stderr)
    accepted_rows: list[dict] = []
    rejected_rows: list[dict] = []
    uncertain_rows: list[dict] = []

    with open(TSV_PATH, newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            word = row["word"]
            sources = parse_sources(row.get("sources", ""))
            dict_source_count = int(row.get("dict_sources") or 0)

            obj: dict = {
                "word": word,
                "description": row.get("description") or None,
                "base": row.get("base") or None,
                "corpus_sources": sources,
                "dict_source_count": dict_source_count,
                "classification_pass": model_pass_label(row.get("model", "")),
                "source": "llm",
                "verified_by": VERIFIED_BY_LLM,
            }

            valid = row.get("valid", "")
            uncertain = row.get("uncertain", "")

            if uncertain == "ja" or uncertain == "true":
                obj["uncertain"] = True
                uncertain_rows.append(obj)
            elif valid == "ja":
                accepted_rows.append(obj)
            else:
                rejected_rows.append(obj)

    # Load expanded word list and find net-new forms
    print("Loading expanded word list...", file=sys.stderr)
    llm_accepted_words = {r["word"] for r in accepted_rows}

    expanded_words: set[str] = set()
    with open(EXPANDED_PATH) as f:
        for line in f:
            w = line.strip()
            if w:
                expanded_words.add(w)

    net_new = expanded_words - llm_accepted_words
    print(f"  Net-new morphological forms: {len(net_new):,}", file=sys.stderr)

    # Build accepted list: LLM-accepted first, then net-new morphological forms
    accepted_words_set = llm_accepted_words | net_new

    morph_rows: list[dict] = []
    for word in sorted(net_new):
        morph_rows.append({
            "word": word,
            "description": None,
            "base": None,
            "corpus_sources": [],
            "dict_source_count": 0,
            "classification_pass": None,
            "source": "morphology",
            "verified_by": VERIFIED_BY_MORPH,
        })

    # Write files
    def write_jsonl(path: Path, rows: list[dict]) -> None:
        with open(path, "w") as f:
            for row in rows:
                f.write(json.dumps(row, ensure_ascii=False) + "\n")
        print(f"  Wrote {len(rows):,} rows → {path}", file=sys.stderr)

    print("Writing output files...", file=sys.stderr)

    all_accepted = sorted(accepted_rows + morph_rows, key=lambda r: r["word"])
    write_jsonl(OUT_ACCEPTED, all_accepted)
    write_jsonl(OUT_REJECTED, sorted(rejected_rows, key=lambda r: r["word"]))
    write_jsonl(OUT_UNCERTAIN, sorted(uncertain_rows, key=lambda r: r["word"]))

    print(f"\nSummary:", file=sys.stderr)
    print(f"  Accepted (LLM):           {len(accepted_rows):>8,}", file=sys.stderr)
    print(f"  Accepted (morphology):    {len(morph_rows):>8,}", file=sys.stderr)
    print(f"  Accepted (total):         {len(all_accepted):>8,}", file=sys.stderr)
    print(f"  Rejected:                 {len(rejected_rows):>8,}", file=sys.stderr)
    print(f"  Uncertain:                {len(uncertain_rows):>8,}", file=sys.stderr)


if __name__ == "__main__":
    main()
